### ISSUE TITLE
Add the option of quiet execution

### ISSUE THREAD

**Issue by christopher-caldwell** [u3u/fix-tsup-cjs#11]
I don't want console logs when running this, is it possible to add the option to silence the output?

**Comment by u3u** [comment]
Okay, I will add it as soon as possible.

**Comment by christopher-caldwell** [comment]
Awesome, thank you!

**Comment by u3u** [comment]
Hi, The `silent` option has been added (https://github.com/u3u/fix-tsup-cjs/releases/tag/v1.2.0). Please try updating and using `fix-tsup-cjs --silent`.
Thank you for your report!

**Comment by christopher-caldwell** [comment]
Looks great! Thanks
